Post:
  fields:
    default: title, tag_list, body
    form: title, tag_list, body
    options:
      templates:
        body: text_with_ckeditor
  order_by: -created_at
  filters: created_at
  search: title
  application: content